---
title: "Anotações sobre o PIB dos municípios de São Paulo"
author: "Fernando Almeida Barbalho"
date: '2025-01-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(colorspace)
library(patchwork)

mapa_sp <- readRDS("mapa_sp.rds")

pib_trabalho <- readRDS("pib_trabalho_2023.rds")

pib_total_sp <- readRDS("pib_total_sp_2023.rds")

mapa_sp_estado <- readRDS("mapa_sp_estado.rds")

mapa_sedes_sp <- readRDS("mapa_sedes_sp.rds")




populacao_municipios_1991_2022 <- read_csv("populacao_municipios_1991_2022.csv")

cor_fundo<- "#D0D0D0"# "#F8F8F8"

cor_fundo_painel<- "#F5F5F5"

cor_fundo_estados<- "#696969"

cor_fundo_mapa_pontos <- "#2B2B2B" #"#505050"

cor_texto<- "#324e5a"


```



```{r fig.width=10, fig.height=8}

#sf::st_as_sf(

# graf1<-
#   sf::st_as_sf(mapa_sp %>%
#   mutate(municipio_codigo = as.character(code_muni))) %>%
#   inner_join(
#     pib_trabalho %>%
#       filter(ano==2023)
#   ) %>%
#   ggplot() +
#   geom_sf(aes(fill=perc)) +
#   scale_fill_continuous_sequential(palette = "Heat 2") +
#   theme_void() +
#   labs(
#     title = "Distribuição do PIB de São Paulo",
#     subtitle = "Todos municípios do Estado",
#     fill = "(%) PIB de SP",
#     caption = "Ano referência: 2023. Fonte: IBGE"
#   )+
#   theme(
#     panel.background = element_rect(fill = "black")
#   )
# 
# 
# 
# graf2<-
#   sf::st_as_sf(mapa_sp %>%
#   mutate(municipio_codigo = as.character(code_muni))) %>%
#   #filter(municipio_codigo != "3550308") %>%
#   inner_join(
#     pib_trabalho %>%
#       filter(ano==2023) %>%
#       mutate(perc = ifelse(municipio_codigo == "3550308",NA,perc))
#   ) %>%
#   ggplot() +
#   geom_sf(aes(fill=perc)) +
#   scale_fill_continuous_sequential(palette = "Heat 2", na.value = "lightgray") +
#   theme_void() +
#   labs(
#     title = "Distribuição do PIB de São Paulo",
#     subtitle = "Todos municípios do Estado menos a capital",
#     fill = "(%) PIB de SP",
#     caption = "Ano referência: 2023. Fonte: IBGE"
#   ) +
#   theme(
#     panel.background = element_rect(fill = "black")
#   )
# 
# graf1 + graf2
```


```{r  fig.dpi=300, fig.width=10, fig.height=6 }

#fig.width=10, fig.height=6

hjust<- c(1,rep(-0.1,19))
cor<- c("white", rep("black",19))

dados_grafico_1<-
  pib_trabalho %>%
  filter (ano==2023) %>%
  arrange(desc(valor)) %>%
  mutate( municipio = str_sub(municipio,1, str_length(municipio)-4),
          municipio = reorder(municipio, valor)) %>%
  slice_max(order_by = valor, n=20) %>% 
  mutate(valor = valor/10^6)
  

proporcao_capital<-
  dados_grafico_1$perc[1]/100

graf1<-
dados_grafico_1 %>%
  ggplot(aes(x=valor, y=municipio))+
  geom_col(aes(fill=valor), show.legend = FALSE)+
  geom_text(aes(label= scales::number(valor, accuracy = 1.0, big.mark = "."), x= valor),
            hjust = -0.1, 
            color = cor_texto, size =3) +
  geom_text(data = tibble(valor = 685, municipio = "Barueri " ),
            aes(label = str_wrap( paste0("São Paulo capital corresponde a ", scales::percent(proporcao_capital, accuracy = 1.0)," do total do PIB paulsta") ,35),),
            color = cor_texto,
            fontface = "bold")+
  geom_curve( data = tibble(valor = 1000, municipio = "São Paulo "),
              aes( xend = 700, yend = "São Bernardo do Campo "),
              curvature = -0.25, ncp = 50,
              arrow = arrow(length = unit(3, "mm"), type = "closed"),
              color = cor_texto
  ) +
  scale_fill_continuous_sequential(palette = "Heat 2", na.value = "lightgray")+
  scale_x_continuous(expand = expansion(mult = c(0.01, 0.15))) +
  theme_light()  +
  theme(
    panel.background =  element_rect( fill= cor_fundo_painel),
    panel.grid =  element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", colour = cor_texto),
    legend.position = "none",
    legend.title = element_blank(),
    legend.background = element_rect(fill= cor_fundo),
    plot.background = element_rect(fill =cor_fundo ),
    plot.title = element_text(size = 12, face = "italic"),
    plot.subtitle = element_text(size = 10, face = "italic"),
    text = element_text( colour = cor_texto),
    axis.text.x =  element_blank()
    #axis.text.y = element_text(color = c(paleta_paises[2]), face = "bold")
    
  ) +
  
  labs(
    title = "Vinte municípios com capital",
    subtitle = "",
    x= "",
    y= ""
  )

dados_grafico_2<-
  pib_trabalho %>%
  filter (ano==2023,
          municipio_codigo != "3550308") %>%
  mutate(municipio = str_sub(municipio,1, str_length(municipio)-4),
          municipio = reorder(municipio, valor)) %>%
  slice_max(order_by = valor, n=20) %>% 
  mutate(valor = valor/10^6)
  
graf2<-
dados_grafico_2 %>%
  ggplot(aes(x=valor, y=municipio))+
  geom_col(aes(fill=valor), show.legend = FALSE)+
  geom_text(aes(label= scales::number(valor, accuracy = 1.0, big.mark = "."), x= valor),hjust = -0.1, color = cor_texto, size =3) +
  scale_fill_continuous_sequential(palette = "Heat 2", na.value = "lightgray")+
  scale_x_continuous(expand = expansion(mult = c(0.01, 0.08))) +
  theme_light()  +
  theme(
    panel.background =  element_rect( fill= cor_fundo_painel),
    panel.grid =  element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", colour = cor_texto),
    legend.position = "none",
    legend.title = element_blank(),
    legend.background = element_rect(fill= cor_fundo),
    plot.background = element_rect(fill =cor_fundo ),
    plot.title = element_text(size = 12, face = "italic"),
    plot.subtitle = element_text(size = 10, face = "italic"),
    text = element_text( colour = cor_texto),
    axis.text.x = element_blank()
    #axis.text.y = element_text(color = c(paleta_paises[2]), face = "bold")
    
  ) +
  labs(
    title = "Vinte municípios sem capital",
    subtitle = "",
    x= "",
    y= ""
  )

graf1 + graf2 + 
  plot_annotation(title = "PIB dos municípios de São Paulo em 2023", 
                  subtitle = "Valores em R$ bilhões", 
                  caption = "Fonte: IBGE. Dados disponibilizados em Dez 2025. Elaboração: VPR/DIESO em 08/01/2026",
                  theme = theme(
                    plot.background = element_rect(fill =cor_fundo),
                    plot.title = element_text(size= 14, face = "bold"),
                    plot.subtitle = element_text(size = 12, face = "italic")
  ) ) 
  

```


```{r}
# # Definindo os intervalos
# intervalos <- c(0, 2000, 5000, 10000, 20000, 50000, 100000, 500000, Inf)
# nomes_faixas <- c("até 2.000", "2.001 a 5.000", "5.001 a 10.000", "10.001 a 20.000", "20.001 a 50.000", "50.001 a 100.000", "100.001 a 500.000", "> 500.000")
# 
# # Adicionando a coluna de faixa populacional
# populacao_municipios_1991_2022$faixa_populacional <- cut(populacao_municipios_1991_2022$populacao, breaks = intervalos, labels = nomes_faixas, right = FALSE)
# 
# 
# 
# populacao_municipios_1991_2022 %>%
#   mutate(municipio_codigo = as.character(id_municipio),
#          ano = as.character(ano)) %>%
#   inner_join(pib_trabalho) %>%
#   summarise(soma_perc = sum(perc),
#             .by= c(ano,faixa_populacional )) %>%
#   ggplot()+
#   geom_col(aes(x=ano, y= soma_perc)) +
#   theme_light() +
#   theme(
#     panel.grid = element_blank(),
#     axis.text.x = element_text(angle = 90),
#     axis.title.x = element_blank()
#   ) +
#   labs(
#     title = "Evolução da soma dos percentuais de PIB",
#     subtitle = "Municípios de São Paulo por faixas de população",
#     y= "soma do percentual do PIB"
#   ) +
#     facet_wrap(faixa_populacional~., scales = "free_y") 
# 
# 

```


```{r}
# populacao_municipios_1991_2022 %>%
#   mutate(municipio_codigo = as.character(id_municipio),
#          ano = as.character(ano)) %>%
#   inner_join(pib_trabalho) %>%
#   summarise(soma_perc = sum(perc),
#             .by= c(ano,faixa_populacional )) %>%
#   ggplot()+
#   geom_col(aes(x=ano, y= soma_perc)) +
#   theme_light() +
#   theme(
#     panel.grid = element_blank(),
#     axis.text.x = element_text(angle = 90),
#     axis.title.x = element_blank()
#   ) +
#   labs(
#     title = "Evolução da soma dos percentuais de PIB",
#     subtitle = "Municípios de São Paulo por faixas de população",
#     y= "soma do percentual do PIB"
#   ) +
#   facet_wrap(faixa_populacional~.) 
# 

```


```{r}

 # top_20_50k<-
 #   (pib_trabalho %>%
 #      filter(ano%in% c(2023),
 #             municipio_codigo %in% mun_pop_entre_50k_100k) %>%
 #  slice_max(order_by = perc, n=20))$municipio_codigo
 #  
 #  
 # pib_trabalho %>%
 #      filter(ano%in% c(2012,2023),
 #             municipio_codigo %in% top_20_50k) %>%
 #  mutate(municipio = str_sub(municipio,1, str_length(municipio)-4),
 #          municipio = reorder(municipio, perc)) %>%
 #  ggplot(aes(x=perc, y=municipio))+
 #  geom_col(aes(fill = perc))+
 #  geom_text(aes(label=round(perc,1)), size =3, hjust=1) +
 #  theme_light() +
 #  theme(
 #    panel.grid = element_blank(),
 #    axis.text.x = element_text(angle = 90)
 #  ) +
 #  scale_fill_continuous_sequential(palette = "Heat 2", na.value = "lightgray")+
 #  labs(
 #    title = "Ranking do PIB das cidades entre 50.000 e 100.000 habitantes",
 #    x= "",
 #    y= "",
 #    fill = "(%) PIB de SP"
 #  ) +
 #  facet_wrap(ano~.)
  
```


```{r}

  # sf::st_as_sf(mapa_sedes_sp %>%
  # mutate(municipio_codigo = as.character(code_muni))) %>%
  # inner_join(
  #   pib_trabalho %>%
  #     filter(ano%in% c(2023),
  #            municipio_codigo %in% top_20_50k)
  # ) %>%
  # ggplot() +
  # geom_sf(aes(fill=perc), pch=21, color = "black", size=1.5) +
  # geom_sf(data= mapa_sp_estado, fill= NA) +
  # scale_fill_continuous_sequential(palette = "Heat 2") +
  # theme_void() +
  # labs(
  #   title = "Distribuição do PIB de São Paulo",
  #   subtitle = "Top 20 municípios entre 50.000 e 100.000 habitantes",
  #   fill = "(%) PIB de SP",
  #   caption = "Ano referência: 2023. Fonte: IBGE"
  # )+
  # theme(
  #   panel.background = element_rect(fill = "black")
  # ) 

```

```{r fig.width=10, fig.height=8}
# contas_pib_sp %>%
#   filter(variavel_codigo %in% c(515, 519, 527, 6572)) %>%
#   mutate(variavel = case_when(
#     variavel_codigo == 515 ~"VA Agropecuária",
#     variavel_codigo == 519 ~"VA Indústria",
#     variavel_codigo == 527 ~"VA Administração",
#     variavel_codigo == 6572 ~"VA Serviços"
#   )) %>%
#   rename(perc = valor) %>%
#   mutate(municipio = str_sub(municipio,1, str_length(municipio)-4),
#           municipio = reorder(municipio, perc)) %>%
#   ggplot(aes(x=perc, y=municipio))+
#   geom_col(aes(fill = perc))+
#   geom_text(aes(label=round(perc,1)), size =3, hjust=1) +
#   theme_light() +
#   theme(
#     panel.grid = element_blank(),
#     axis.text.x = element_text(angle = 90)
#   ) +
#   scale_fill_continuous_sequential(palette = "Heat 2", na.value = "lightgray")+
#   labs(
#     title = "Ranking do PIB das cidades entre 50.000 e 100.000 habitantes",
#     subtitle = "(%) Valor Adicionado Bruto de SP",
#     x= "",
#     y= "",
#     fill = "(%) VA"
#   ) +
#   facet_wrap(ano+variavel~., ncol = 4) 
#   
```

